# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gYCyBXLplLukViPvbSaJqff4s-z8i-Fd
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,accuracy_score,classification_report
from sklearn import svm
from sklearn.svm import SVC,LinearSVC
from sklearn.metrics import confusion_matrix

df = pd.read_csv("https://raw.githubusercontent.com/faizan619/Elitian_Collab/main/PracticalCodes/AI/diabetes.csv")
df

x = df.drop("Outcome",axis=1)
y = df["Outcome"]

X_train = x.iloc[:600]
X_test = x.iloc[600:]
y_train = y[:600]
y_test = y[600:]

print("X_train Shape :",X_train.shape)
print("X_test Shape :",X_test.shape)
print("Y_train shape :",y_train.shape)
print("Y_test shape :",y_test.shape)

from sklearn.svm import SVC
s_v_c = SVC(kernel="linear").fit(X_train, y_train)

s_v_c

y_pred = s_v_c.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
cm

accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))